### PR TITLE
Contains the wc fixes and the massive overhaul commit.

### PR DESCRIPTION
**Pull request by grobe0ba**
@pannon @skarekrow This PR represents the previous overhaul branch from me and the wc fixes.

### CODE REVIEW

**Comment by pr1ntf** [comment]
Patch works on all functions I tried.

**Comment by skarekrow** [comment]
@grobe0ba I'm testing one last thing with this commit but otherwise it LGTM :+1: Will merge shortly. Thanks for this.

**Comment by grobe0ba** [comment]
As soon as this is merged, I can push a split version. Whilst I am waiting, I can figure out a few sourcing dependency issues I'm running into. I think you'll like the end results though.

**Comment by skarekrow** [comment]
Sounds good, just about ending my testing. Waiting on it now.

**Comment by grobe0ba** [comment]
@pannon @skarekrow 

I present to you my vision of a split.

**Comment by grobe0ba** [comment]
Fixed PR merge that I missed.

**Comment by skarekrow** [comment]
Incredible speed @grobe0ba. You're a beast. Will merge this now so we can all test it.

**Comment by pannon** [comment]
@grobe0ba we will need to rename you to Mr. Tornado ;)

**Comment by grobe0ba** [comment]
Thanks for the compliments gents. You guys are the ones that gave me an excellent starting base to work from. I was trolling through the ports tree, found this, and decided to see if it was better than qjail. Needless to say, I immediately migrated all my jails and started submitting PR's.

**Comment by skarekrow** [comment]
We are better for it. Sorry for the slightly rough introduction. It just was a LOT for one of the first PR's we've had from you. Just protecting iocage so it continues to be awesome.

**Comment by pannon** [comment]
Welcome aboard Byron!

**Comment by grobe0ba** [comment]
I completely understand the reluctance, especially after the debacle that was my PR for the 9.3 fixes.
A PR this size from someone on ANY project should be carefully reviewed.

**Comment by skarekrow** [comment]
Yes. Now that it's in develop, everyone can bang on it for a little while and then we can hopefully tag the next major version. This was *huge* thank you for this.

**Comment by grobe0ba** [comment]
Y'alls are more than welcome!

**Comment by pr1ntf** [comment]
You should reactivate that twitter account and hang out some time!

**Comment by grobe0ba** [comment]
I suppose I could. I only ever used it for testing something a friend was working on.

**Comment by skarekrow** [comment]
It's a great way to stay in contact. Or questions. I'm @bschneider0922 and
Peters is @pannonp.

**Comment by grobe0ba** [comment]
Yah, I already hit the follow button on y'alls.

**Comment by skarekrow** [comment]
Great!

**Comment by pr1ntf** [comment]
If you have gmail, we can also start a group hangout if that's more your style.

**Comment by pannon** [comment]
+1 for hangout

**Comment by skarekrow** [comment]
:+1:

**Comment by skarekrow** [comment]
:+1:

**Pull request merged**
