### PR TITLE
libiocage: update command

### PR DESCRIPTION
**Pull request by gronke**
- Deprecate upgrade command
- Copy update command from libiocage/ioc

### CODE REVIEW

**Comment by skarekrow** [comment]
Why the removal of upgrade? Update != Upgrade in FreeBSD after all.

**Review by skarekrow — CHANGES_REQUESTED** [review]
Should have selected request changes on this :D

**Comment by gronke** [comment]
> Why the removal of upgrade? Update != Upgrade in FreeBSD after all.

It is solved in the update command logic. It applies the updates that have been fetched for the release, but it is only necessary if it is not a basejail. The `fetch` command downloads the updates while `update` installs them to a target jail.

After updating a jail it is still recommended to update the packages and run mergemaster, but this ~~is~~ can be a manual process.

**Comment by skarekrow** [comment]
I don't think we're talking about the same thing. Updating is patch level. Upgrading is moving from another world to a new one. 

IE 11.1-RELEASE -> 11.2-RELEASE
Update is 11.1-RELEASE -> 11.1-RELEASE-p4

If we are talking about the same thing, you must not confuse those terms, hence the separate commands. They are very different with different goals.

**Pull request closed without merging**
