### PR TITLE
tkt-74281: Use hosts pkgs to remove pkgs for plugins

### PR DESCRIPTION
**Pull request by skarekrow**
- Make revoked directory on plugin install
- Remove unused variable

FreeNAS Ticket: #74281

### CODE REVIEW

**Review by sonicaj — COMMENTED** [review]
I think we have a leftover usage of update which needs to be updated as we don't pass jid there at upgrade ?

**Comment by skarekrow** [comment]
Where?

**Comment by sonicaj** [comment]
Line 1092 ioc_plugin

**Comment by skarekrow** [comment]
That's unrelated

**Comment by sonicaj** [comment]
I think it will fail as we don't pass jid there and it's not a default argument in update function so that will raise an exception ?

**Review by sonicaj — APPROVED** [review]

**Comment by skarekrow** [comment]
Unrelated failure, merging.

**Pull request merged**
