### PR TITLE
 - Add a new Makefile which will install iocage into FreeBSD

### PR DESCRIPTION
**Pull request by kmoore134**
Added a really basic Makefile, so you can run "make install" and end up with iocage and related bits in /usr/local or whatever PREFIX

Feel free to expand upon this, but it satisfies my laziness at the moment.

### CODE REVIEW

**Comment by pr1ntf** [comment]
+1

**Comment by skarekrow** [comment]
No need to +1 ;) Kris go ahead and just push to develop man! I can't login
to GH on my phone atm.

**Comment by kmoore134** [comment]
Says I still don't have write access...

**Comment by skarekrow** [comment]
Did you accept the invitation? I for sure gave you it.

**Comment by kmoore134** [comment]
Yep, it said I was in the group, not sure what the deal is.

**Comment by skarekrow** [comment]
Like a minute from the ranch, will figure it out then haha.

**Pull request merged**
