### PR TITLE
 Fixed bug: Jail fails to start when depends jail is already running (#608)

### PR DESCRIPTION
**Pull request by thedix**
The idea is to try starting all the nested jails.

### CODE REVIEW

**Review by skarekrow — CHANGES_REQUESTED** [review]
We should create a new exception and return that when a jail is already running. Then we can reliably catch it here. See ioc_exceptions for that

**Comment by thedix** [comment]
Ok, I have to take some time for this.

**Comment by thedix** [comment]
Check this out.

I added new exception JailRunning and new property IOCStart.is_depend which is True for all the nested jail when starting. If is_depend==True then IOCStart.__start_jail__() raises JailRunning for starting jail. If is_depend==False then __start_jail__() raises SystemExit(1) as usual (this is a parent jail). Also I modified default callback() function and added new argument "force_raise" to force raising exception when there is a valid TTY. Previous code raised exception only without TTY. Method IOCage.start() processes all the dependent jails with setting is_depend=True for each and reverting previous value after call finished. 

Now the logic is the following: parent jail is not started if depended jails failed to start. If depended jails are already started then start parent jail.

**Review by skarekrow — APPROVED** [review]

**Comment by skarekrow** [comment]
Great change, thanks!

**Pull request merged**
