### PR TITLE
fix broken commands

### LINKED ISSUE #894: commands on iocage-devel release are borked
Is there some update command I am supposed to run when moving from py36-iocage-0.9.10 to py36-iocage-devel-1.0.0.20190308,1?

```
[dan@x8dtu:~] $ iocage -v
Version	1.2 BETA

[dan@x8dtu:~] $ sudo iocage list
Usage: iocage [OPTIONS] COMMAND [ARGS]...
Try "iocage --help" for help.

Error: No such command "list".


[dan@x8dtu:~] $ sudo iocage get all x8dtu-pg01
Usage: iocage [OPTIONS] COMMAND [ARGS]...
Try "iocage --help" for help.

Error: No such command "get".

[dan@x8dtu:~] $ iocage snapshot
Usage: iocage [OPTIONS] COMMAND [ARGS]...
Try "iocage --help" for help.

Error: No such command "snapshot".
```

This seems ominous as if there are only a few commands available:
```

[dan@x8dtu:/var/cache/pkg] $ iocage 
Usage: iocage [OPTIONS] COMMAND [ARGS]...

  A jail manager.

Options:
  -v, --version  Display iocage's version and exit.
  -f, --force    Allow iocage to rename datasets.
  -D, --debug    Log debug output to the console.
  --help         Show this message and exit.

Commands:
  migrate  Migrate all iocage_legacy develop basejails to new clonejails.

```

### PR DESCRIPTION
**Pull request by dlangille**
Fixes #894

Make sure to follow and check these boxes before submitting a PR! Thank you.

- [ ] Explain the feature
- [ ] Read [CONTRIBUTING.md](https://github.com/iocage/iocage/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by sonicaj** [comment]
@dlangille i think the rc script comes from the port for the issue you have pointed out

**Review by skarekrow — APPROVED** [review]

**Comment by skarekrow** [comment]
Regardless, we should still set PATH as a good practice. Thanks @dlangille

**Comment by dlangille** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=239759 contains the appropriate patch as well.

**Comment by dlangille** [comment]
FYI, looks like the port uses the rc.d script from this repo.

**Pull request merged**
