### PR TITLE
NAS-102987 / 11.3 / Add ability to retrieve default properties

### PR DESCRIPTION
**Pull request by sonicaj**
This commit adds ability to retrieve default properties without initializing the iocage dataset.

### CODE REVIEW

**Comment by skarekrow** [comment]
What's the point of this though? Default props are only useful if we're working with jails. So we initialize them then, as we may need to migrate the default props, or jail props if the default props changed.

**Comment by sonicaj** [comment]
If we want to show reasonable defaults of a jail for systems which have integrated iocage, We should be able to do that without initializing the datasets.

**Comment by skarekrow** [comment]
I disagree, this is relying on those datasets to exist to read that configuration. If they're missing, the file doesn't exist to read the default props from.

**Comment by sonicaj** [comment]
If iocage has been initialized, then it's the user/dev's responsibility to expose the `True` defaults as per config. The point is to not initialize the datasets and still be able to expose defaults for the UI

**Review by skarekrow — APPROVED** [review]

**Comment by sonicaj** [comment]
Thank you ;)

**Pull request merged**
