### PR TITLE
Adds [-c | --count] flag documentation to clone subcommand

### PR DESCRIPTION
**Pull request by wxcafe**
- [x] Explain the feature
    documents [-c | --count] flag for the clone subcommand as explained in iocage/iocage#389
- [x] Read [CONTRIBUTING.md](https://github.com/iocage/iocage/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by skarekrow** [comment]
Thanks!

**Comment by wxcafe** [comment]
Sure! btw, I asked in the IRC channel but got no response: are the _all, _pool, _long, and so on in the various "options" fields on purpose? like this : 
screenshot from 2017-10-16 22-31-25

**Comment by skarekrow** [comment]
I’d ignore those. They’re internal as they would collide in namespaces. Just stick to the short and long flags.

**Comment by wxcafe** [comment]
I mean, yeah, but I'm pretty sure they should be removed from the man page, since they're not in the --help output and can't be used

**Comment by skarekrow** [comment]
Hah yes absolutely. @Mrt134 ping :D

**Pull request merged**
