### PR TITLE
[WIP] Logfile

### PR DESCRIPTION
**Pull request by Licenser**
This is the start of adding a logfile. WIP please don't merge yet

### CODE REVIEW

**Comment by Licenser** [comment]
The Travis error seems is related to permissions on the log file.

**Comment by skarekrow** [comment]
Ignore Travis, I'll be removing that anyways and using something FreeBSD instead.

**Comment by skarekrow** [comment]
So all good except for the `print` in the libs as I noted in #81. Thanks for going down this rabbit hole :D

**Comment by Licenser** [comment]
based on #81 it seems this really requires a rewrite of a lot of the lib code, I'll close this and just keep my fork for the time being.

**Comment by skarekrow** [comment]
Appreciate the effort @Licenser, sorry it turned out to be such a minefield!

**Comment by Licenser** [comment]
No worries while I of cause don't like it I perfectly understand ;). Your work, your software your rules I'm literally just now having the same situation from the opposite side of the table so I sympathize fully.

**Comment by skarekrow** [comment]
Heh, logging is a bitch! My buddy @araujobsd will be taking this and doing all the nasty work. So this situation should improve someday soon :D

**Pull request closed without merging**
