### PR TITLE
Improve testing

### PR DESCRIPTION
**Pull request by lpefferkorn**
Hello Brandon,

Here are some improvements for testing:
* clearly separating unit tests from functional tests with dedicated subdirectories
* adding pep8 checks when running unit tests. If something is not compliant it is considered as an error.
* all the tests can simply be started by running **pytest**
* all the unit tests do not need root access to be started
* if the **--zpool** parameter has been forgotten, pytest will stop immediately
* if **pytest** is started as root, pytest will detect it and run unit tests + functional tests as well
* Every time tests are started, code coverage will be displayed.

The idea is also to integrate root access and parameters needed by the functional tests to pytest, so it will help the user knowing what is going on and stops gracefully.

Examples:

### Starting pytest as normal user
```
$ pytest
================================================================ test session starts =================================================================
platform freebsd11 -- Python 3.6.0, pytest-3.0.6, py-1.4.32, pluggy-0.4.0 -- /usr/home/loic/iocage/bin/python3.6
cachedir: .cache
rootdir: /usr/home/loic/iocage.git, inifile: setup.cfg
plugins: pep8-1.0.6, flake8-0.8.1, cov-2.4.0
collected 20 items

iocage/tests/functional_tests/0001_ioc_activate_test.py::test_activate SKIPPED
iocage/tests/functional_tests/0002_ioc_check_test.py::test_check SKIPPED
iocage/tests/functional_tests/0003_ioc_fetch_test.py::test_fetch SKIPPED
iocage/tests/functional_tests/0004_ioc_create_test.py::test_create SKIPPED
iocage/tests/functional_tests/0005_ioc_start_test.py::test_start SKIPPED
iocage/tests/functional_tests/0006_ioc_stop_test.py::test_stop SKIPPED
iocage/tests/functional_tests/0007_ioc_set_test.py::test_set SKIPPED
iocage/tests/functional_tests/0008_ioc_get_test.py::test_get SKIPPED
iocage/tests/functional_tests/0009_ioc_destroy_test.py::test_destroy SKIPPED
iocage/tests/functional_tests/9999_ioc_clean_test.py::test_clean SKIPPED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_get_zfs_pools_multiple_pools PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_get_zfs_pools_one_pool PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_get_zfs_pools_no_pool PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_get_zfs_pools_bad_parameter PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_set_zfs_pool_active_property_bad_param_zpool_name PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_set_zfs_pool_active_property_bad_param_activate PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_set_zfs_pool_active_property_ok PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_set_zfs_pool_active_property_fail PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_set_zfs_pool_comment_bad_param PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_set_zfs_pool_comment_fail PASSED

--------- coverage: platform freebsd11, python 3.6.0-final-0 ---------
Name                        Stmts   Miss Branch BrPart  Cover   Missing
-----------------------------------------------------------------------
iocage/__init__.py              0      0      0      0   100%
iocage/cli/__init__.py          0      0      0      0   100%
iocage/cli/activate.py         56     14     26      1    72%   104-129, 91->exit
iocage/cli/clean.py            37     37     20      0     0%   2-57
iocage/cli/console.py          41     41     20      0     0%   2-68
iocage/cli/create.py           59     59     24      0     0%   2-96
iocage/cli/deactivate.py       13     13      0      0     0%   2-23
iocage/cli/destroy.py          40     40     20      0     0%   2-63
iocage/cli/df.py               40     40      8      0     0%   2-68
iocage/cli/exec.py             34     34     16      0     0%   2-58
iocage/cli/export.py           70     70     20      0     0%   2-108
iocage/cli/fetch.py            43     43     16      0     0%   3-82
iocage/cli/fstab.py            44     44     14      0     0%   2-77
iocage/cli/get.py             101    101     50      0     0%   2-153
iocage/cli/import.py           54     54     10      0     0%   2-80
iocage/cli/list.py             24     24      8      0     0%   3-45
iocage/cli/migrate.py          59     59     12      0     0%   2-102
iocage/cli/pkg.py              23     23      8      0     0%   2-38
iocage/cli/restart.py          70     70     30      0     0%   2-120
iocage/cli/rollback.py         41     41     14      0     0%   2-70
iocage/cli/set.py              38     38     16      0     0%   2-63
iocage/cli/snaplist.py         51     51     22      0     0%   2-85
iocage/cli/snapremove.py       31     31     10      0     0%   2-50
iocage/cli/snapshot.py         36     36     12      0     0%   2-58
iocage/cli/start.py            66     66     34      0     0%   2-106
iocage/cli/stop.py             60     60     28      0     0%   2-94
iocage/cli/update.py           46     46     22      0     0%   2-71
iocage/cli/upgrade.py          70     70     32      0     0%   2-121
iocage/lib/__init__.py          0      0      0      0   100%
iocage/lib/ioc_check.py        32     23     16      0    19%   15-21, 28-61
iocage/lib/ioc_clean.py        69     56     24      0    14%   16-18, 23-30, 34-71, 75-81, 85-117
iocage/lib/ioc_common.py      104     88     42      0    11%   13-32, 40-74, 80-103, 123-134, 158-169, 174-176, 181-186, 191-193
iocage/lib/ioc_create.py      170    151     60      0     8%   23-38, 46-173, 180-303, 310-362, 369-409, 413-431
iocage/lib/ioc_destroy.py      40     31      2      0    21%   16-25, 29-37, 41-61, 65-69
iocage/lib/ioc_exec.py         45     36     16      0    15%   16-24, 28-72
iocage/lib/ioc_fetch.py       514    475    232      0     5%   34-66, 71-90, 98-127, 131-175, 186-292, 304-343, 350-364, 371-452, 456-543, 549-559, 564-624, 628-770, 774-808, 817-836, 842-857, 864-877
iocage/lib/ioc_fstab.py        50     50     14      0     0%   2-88
iocage/lib/ioc_json.py        391    368    152      0     4%   15-18, 28-33, 37-53, 57-105, 109-205, 209-210, 215-307, 312-397, 403-404, 411-472, 479-669, 673-681, 684-713, 717-772
iocage/lib/ioc_list.py        135    123     66      0     6%   22-28, 33-112, 116-198, 202-217, 222-227
iocage/lib/ioc_start.py       226    210     68      0     5%   22-35, 48-291, 296-380, 384-387, 390-401, 409-438
iocage/lib/ioc_stop.py         89     81     40      0     6%   14-27, 30-165
iocage/main.py                 66     66     30      0     0%   2-98
-----------------------------------------------------------------------
TOTAL                        3178   2963   1254      1     5%

============================================================== short test summary info ===============================================================
SKIP [10] /usr/home/loic/iocage.git/iocage/tests/conftest.py:37: Need to be root to run

======================================================= 10 passed, 10 skipped in 0.96 seconds ================================================
```
* Code coverage provided (and line numbers of code that misses tests)
* All the unit tests have been started *(iocage/tests/unit_tests/1000_cli_activate_test.py)*
* The functional tests where root access is needed where skipped, this is reported and explained on the last line

### Starting pytest with sudo
```
$ sudo pytest
================================================================ test session starts =================================================================
platform freebsd11 -- Python 3.6.0, pytest-3.0.6, py-1.4.32, pluggy-0.4.0 -- /usr/home/loic/iocage/bin/python3.6
cachedir: .cache
rootdir: /usr/home/loic/iocage.git, inifile: setup.cfg
plugins: pep8-1.0.6, flake8-0.8.1, cov-2.4.0
collected 20 items

iocage/tests/functional_tests/0001_ioc_activate_test.py::test_activate SKIPPED
iocage/tests/functional_tests/0002_ioc_check_test.py::test_check SKIPPED
iocage/tests/functional_tests/0003_ioc_fetch_test.py::test_fetch SKIPPED
iocage/tests/functional_tests/0004_ioc_create_test.py::test_create SKIPPED
iocage/tests/functional_tests/0005_ioc_start_test.py::test_start SKIPPED
iocage/tests/functional_tests/0006_ioc_stop_test.py::test_stop SKIPPED
iocage/tests/functional_tests/0007_ioc_set_test.py::test_set SKIPPED
iocage/tests/functional_tests/0008_ioc_get_test.py::test_get SKIPPED
iocage/tests/functional_tests/0009_ioc_destroy_test.py::test_destroy SKIPPED
iocage/tests/functional_tests/9999_ioc_clean_test.py::test_clean SKIPPED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_get_zfs_pools_multiple_pools PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_get_zfs_pools_one_pool PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_get_zfs_pools_no_pool PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_get_zfs_pools_bad_parameter PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_set_zfs_pool_active_property_bad_param_zpool_name PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_set_zfs_pool_active_property_bad_param_activate PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_set_zfs_pool_active_property_ok PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_set_zfs_pool_active_property_fail PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_set_zfs_pool_comment_bad_param PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_set_zfs_pool_comment_fail PASSED

--------- coverage: platform freebsd11, python 3.6.0-final-0 ---------
Name                        Stmts   Miss Branch BrPart  Cover   Missing
-----------------------------------------------------------------------
iocage/__init__.py              0      0      0      0   100%
iocage/cli/__init__.py          0      0      0      0   100%
iocage/cli/activate.py         56     14     26      1    72%   104-129, 91->exit
iocage/cli/clean.py            37     37     20      0     0%   2-57
iocage/cli/console.py          41     41     20      0     0%   2-68
iocage/cli/create.py           59     59     24      0     0%   2-96
iocage/cli/deactivate.py       13     13      0      0     0%   2-23
iocage/cli/destroy.py          40     40     20      0     0%   2-63
iocage/cli/df.py               40     40      8      0     0%   2-68
iocage/cli/exec.py             34     34     16      0     0%   2-58
iocage/cli/export.py           70     70     20      0     0%   2-108
iocage/cli/fetch.py            43     43     16      0     0%   3-82
iocage/cli/fstab.py            44     44     14      0     0%   2-77
iocage/cli/get.py             101    101     50      0     0%   2-153
iocage/cli/import.py           54     54     10      0     0%   2-80
iocage/cli/list.py             24     24      8      0     0%   3-45
iocage/cli/migrate.py          59     59     12      0     0%   2-102
iocage/cli/pkg.py              23     23      8      0     0%   2-38
iocage/cli/restart.py          70     70     30      0     0%   2-120
iocage/cli/rollback.py         41     41     14      0     0%   2-70
iocage/cli/set.py              38     38     16      0     0%   2-63
iocage/cli/snaplist.py         51     51     22      0     0%   2-85
iocage/cli/snapremove.py       31     31     10      0     0%   2-50
iocage/cli/snapshot.py         36     36     12      0     0%   2-58
iocage/cli/start.py            66     66     34      0     0%   2-106
iocage/cli/stop.py             60     60     28      0     0%   2-94
iocage/cli/update.py           46     46     22      0     0%   2-71
iocage/cli/upgrade.py          70     70     32      0     0%   2-121
iocage/lib/__init__.py          0      0      0      0   100%
iocage/lib/ioc_check.py        32     23     16      0    19%   15-21, 28-61
iocage/lib/ioc_clean.py        69     56     24      0    14%   16-18, 23-30, 34-71, 75-81, 85-117
iocage/lib/ioc_common.py      104     88     42      0    11%   13-32, 40-74, 80-103, 123-134, 158-169, 174-176, 181-186, 191-193
iocage/lib/ioc_create.py      170    151     60      0     8%   23-38, 46-173, 180-303, 310-362, 369-409, 413-431
iocage/lib/ioc_destroy.py      40     31      2      0    21%   16-25, 29-37, 41-61, 65-69
iocage/lib/ioc_exec.py         45     36     16      0    15%   16-24, 28-72
iocage/lib/ioc_fetch.py       514    475    232      0     5%   34-66, 71-90, 98-127, 131-175, 186-292, 304-343, 350-364, 371-452, 456-543, 549-559, 564-624, 628-770, 774-808, 817-836, 842-857, 864-877
iocage/lib/ioc_fstab.py        50     50     14      0     0%   2-88
iocage/lib/ioc_json.py        391    368    152      0     4%   15-18, 28-33, 37-53, 57-105, 109-205, 209-210, 215-307, 312-397, 403-404, 411-472, 479-669, 673-681, 684-713, 717-772
iocage/lib/ioc_list.py        135    123     66      0     6%   22-28, 33-112, 116-198, 202-217, 222-227
iocage/lib/ioc_start.py       226    210     68      0     5%   22-35, 48-291, 296-380, 384-387, 390-401, 409-438
iocage/lib/ioc_stop.py         89     81     40      0     6%   14-27, 30-165
iocage/main.py                 66     66     30      0     0%   2-98
-----------------------------------------------------------------------
TOTAL                        3178   2963   1254      1     5%

============================================================== short test summary info ===============================================================
SKIP [10] /usr/home/loic/iocage.git/iocage/tests/conftest.py:40: Need --zpool option to run

======================================================= 10 passed, 10 skipped in 0.94 seconds ========================================================
```

Very similar to the previous output, functional tests were also skipped because the **--zpool** option has not been set (also explained on the last line)

### Starting pytest with sudo and --zpool
```
$ sudo pytest --zpool tank1
================================================================ test session starts =================================================================
platform freebsd11 -- Python 3.6.0, pytest-3.0.6, py-1.4.32, pluggy-0.4.0 -- /usr/home/loic/iocage/bin/python3.6
cachedir: .cache
rootdir: /usr/home/loic/iocage.git, inifile: setup.cfg
plugins: pep8-1.0.6, flake8-0.8.1, cov-2.4.0
collected 20 items

iocage/tests/functional_tests/0001_ioc_activate_test.py::test_activate PASSED
iocage/tests/functional_tests/0002_ioc_check_test.py::test_check PASSED
iocage/tests/functional_tests/0003_ioc_fetch_test.py::test_fetch PASSED
iocage/tests/functional_tests/0004_ioc_create_test.py::test_create PASSED
iocage/tests/functional_tests/0005_ioc_start_test.py::test_start PASSED
iocage/tests/functional_tests/0006_ioc_stop_test.py::test_stop PASSED
iocage/tests/functional_tests/0007_ioc_set_test.py::test_set PASSED
iocage/tests/functional_tests/0008_ioc_get_test.py::test_get PASSED
iocage/tests/functional_tests/0009_ioc_destroy_test.py::test_destroy PASSED
iocage/tests/functional_tests/9999_ioc_clean_test.py::test_clean PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_get_zfs_pools_multiple_pools PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_get_zfs_pools_one_pool PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_get_zfs_pools_no_pool PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_get_zfs_pools_bad_parameter PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_set_zfs_pool_active_property_bad_param_zpool_name PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_set_zfs_pool_active_property_bad_param_activate PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_set_zfs_pool_active_property_ok PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_set_zfs_pool_active_property_fail PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_set_zfs_pool_comment_bad_param PASSED
iocage/tests/unit_tests/1000_cli_activate_test.py::test_set_zfs_pool_comment_fail PASSED

--------- coverage: platform freebsd11, python 3.6.0-final-0 ---------
Name                        Stmts   Miss Branch BrPart  Cover   Missing
-----------------------------------------------------------------------
iocage/__init__.py              0      0      0      0   100%
iocage/cli/__init__.py          0      0      0      0   100%
iocage/cli/activate.py         56     14     26      1    72%   104-129, 91->exit
iocage/cli/clean.py            37     37     20      0     0%   2-57
iocage/cli/console.py          41     41     20      0     0%   2-68
iocage/cli/create.py           59     59     24      0     0%   2-96
iocage/cli/deactivate.py       13     13      0      0     0%   2-23
iocage/cli/destroy.py          40     40     20      0     0%   2-63
iocage/cli/df.py               40     40      8      0     0%   2-68
iocage/cli/exec.py             34     34     16      0     0%   2-58
iocage/cli/export.py           70     70     20      0     0%   2-108
iocage/cli/fetch.py            43     43     16      0     0%   3-82
iocage/cli/fstab.py            44     44     14      0     0%   2-77
iocage/cli/get.py             101    101     50      0     0%   2-153
iocage/cli/import.py           54     54     10      0     0%   2-80
iocage/cli/list.py             24     24      8      0     0%   3-45
iocage/cli/migrate.py          59     59     12      0     0%   2-102
iocage/cli/pkg.py              23     23      8      0     0%   2-38
iocage/cli/restart.py          70     70     30      0     0%   2-120
iocage/cli/rollback.py         41     41     14      0     0%   2-70
iocage/cli/set.py              38     38     16      0     0%   2-63
iocage/cli/snaplist.py         51     51     22      0     0%   2-85
iocage/cli/snapremove.py       31     31     10      0     0%   2-50
iocage/cli/snapshot.py         36     36     12      0     0%   2-58
iocage/cli/start.py            66     66     34      0     0%   2-106
iocage/cli/stop.py             60     60     28      0     0%   2-94
iocage/cli/update.py           46     46     22      0     0%   2-71
iocage/cli/upgrade.py          70     70     32      0     0%   2-121
iocage/lib/__init__.py          0      0      0      0   100%
iocage/lib/ioc_check.py        32      3     16      4    85%   19, 46, 53, 18->19, 45->46, 49->40, 52->53
iocage/lib/ioc_clean.py        69     33     24      4    43%   27-30, 44-46, 56, 62-63, 80-81, 85-117, 26->27, 55->56, 66->70, 70->exit
iocage/lib/ioc_common.py      104     69     42      2    25%   13-32, 40-74, 80-103, 134, 166-167, 174-176, 181-186, 131->134, 165->166
iocage/lib/ioc_create.py      170     72     60     11    52%   38, 54, 57, 67, 75-80, 86-103, 111-112, 128-129, 134-136, 146-160, 167-171, 310-362, 372, 400-409, 37->38, 53->54, 56->57, 65->67, 85->86, 123->140, 127->128, 145->146, 162->166, 166->167, 383->400
iocage/lib/ioc_destroy.py      40      8      2      1    79%   25, 36-37, 47-48, 57, 68-69, 24->25
iocage/lib/ioc_exec.py         45     36     16      0    15%   16-24, 28-72
iocage/lib/ioc_fetch.py       514    329    232     27    31%   44, 57-62, 66, 77, 98-127, 132-133, 136-172, 186-292, 308-321, 328-329, 339-340, 356-362, 379-396, 403-404, 411, 427-441, 449-450, 469-508, 540-541, 565, 568-572, 593-605, 621-622, 628-770, 774-808, 817-836, 842-857, 41->44, 56->57, 64->66, 76->77, 85->79, 131->132, 134->136, 307->308, 338->339, 342->exit, 353->358, 374->exit, 378->379, 410->411, 417->444, 426->427, 444->406, 459->465, 465->exit, 468->469, 509->exit, 514->543, 564->565, 567->568, 590->617, 592->593, 618->624
iocage/lib/ioc_fstab.py        50     50     14      0     0%   2-88
iocage/lib/ioc_json.py        391    288    152     17    26%   15-18, 37-53, 57-105, 115-195, 201-203, 238-240, 246-251, 255-287, 295-296, 298-300, 305, 337-373, 388, 393-397, 411-472, 589-600, 606, 611-662, 665, 669, 673-681, 684-713, 717-772, 200->201, 237->238, 242->255, 245->246, 297->298, 304->305, 330->336, 336->337, 381->386, 386->exit, 387->388, 392->393, 588->589, 605->606, 608->611, 664->665, 668->669
iocage/lib/ioc_list.py        135     89     66      6    29%   40-53, 60, 71-73, 87-90, 93-101, 104-112, 116-198, 202-217, 33->40, 59->60, 61->104, 69->71, 86->87, 92->93
iocage/lib/ioc_start.py       226    113     68     18    45%   33, 86, 93-102, 105-129, 135-136, 143-145, 174-175, 221, 235-267, 283, 291, 297-380, 385, 393-396, 398, 409-438, 32->33, 52->291, 85->86, 92->93, 104->105, 134->135, 142->143, 151->174, 159->162, 162->165, 220->221, 226->232, 234->235, 282->283, 296->297, 384->385, 392->393, 397->398
iocage/lib/ioc_stop.py         89     46     40     10    41%   25, 35, 49, 54-87, 92-99, 103-121, 127-145, 153, 24->25, 34->35, 48->49, 53->54, 91->92, 101->125, 102->103, 125->149, 126->127, 152->153
iocage/main.py                 66     66     30      0     0%   2-98
-----------------------------------------------------------------------
TOTAL                        3178   2407   1254    101    21%


============================================================ 20 passed in 119.50 seconds =============================================================
``` 

Since all the prerequisities have been met, all the unit and functional tests have been run :)

### Pep8 tests

Also when **pytest** is started, everything that is not pep8 compliant will be reported as an error:
```
$ pytest
================================================================ test session starts =================================================================
platform freebsd11 -- Python 3.6.0, pytest-3.0.6, py-1.4.32, pluggy-0.4.0 -- /usr/home/loic/iocage/bin/python3.6
cachedir: .cache
rootdir: /usr/home/loic/iocage.git, inifile: setup.cfg
plugins: pep8-1.0.6, flake8-0.8.1, cov-2.4.0
collected 74 items

iocage/__init__.py PASSED
iocage/main.py PASSED
iocage/cli/__init__.py PASSED
iocage/cli/activate.py PASSED
iocage/cli/clean.py PASSED
iocage/cli/console.py PASSED
iocage/cli/create.py PASSED
iocage/cli/deactivate.py PASSED
iocage/cli/destroy.py PASSED
iocage/cli/df.py PASSED
iocage/cli/exec.py PASSED
iocage/cli/export.py PASSED
iocage/cli/fetch.py PASSED
iocage/cli/fstab.py PASSED
iocage/cli/get.py PASSED
iocage/cli/import.py PASSED
iocage/cli/list.py PASSED
iocage/cli/migrate.py PASSED
iocage/cli/pkg.py PASSED
iocage/cli/restart.py PASSED
iocage/cli/rollback.py PASSED
iocage/cli/set.py PASSED
iocage/cli/snaplist.py PASSED
iocage/cli/snapremove.py PASSED
iocage/cli/snapshot.py PASSED
iocage/cli/start.py PASSED
iocage/cli/stop.py FAILED

--------- coverage: platform freebsd11, python 3.6.0-final-0 ---------
Name                        Stmts   Miss Branch BrPart  Cover   Missing
-----------------------------------------------------------------------
iocage/__init__.py              0      0      0      0   100%
iocage/cli/__init__.py          0      0      0      0   100%
iocage/cli/activate.py         56     43     26      0    16%   21-29, 44-66, 81-92, 104-129
iocage/cli/clean.py            37     37     20      0     0%   2-57
iocage/cli/console.py          41     41     20      0     0%   2-68
iocage/cli/create.py           59     59     24      0     0%   2-96
iocage/cli/deactivate.py       13     13      0      0     0%   2-23
iocage/cli/destroy.py          40     40     20      0     0%   2-63
iocage/cli/df.py               40     40      8      0     0%   2-68
iocage/cli/exec.py             34     34     16      0     0%   2-58
iocage/cli/export.py           70     70     20      0     0%   2-108
iocage/cli/fetch.py            43     43     16      0     0%   3-82
iocage/cli/fstab.py            44     44     14      0     0%   2-77
iocage/cli/get.py             101    101     50      0     0%   2-153
iocage/cli/import.py           54     54     10      0     0%   2-80
iocage/cli/list.py             24     24      8      0     0%   3-45
iocage/cli/migrate.py          59     59     12      0     0%   2-102
iocage/cli/pkg.py              23     23      8      0     0%   2-38
iocage/cli/restart.py          70     70     30      0     0%   2-120
iocage/cli/rollback.py         41     41     14      0     0%   2-70
iocage/cli/set.py              38     38     16      0     0%   2-63
iocage/cli/snaplist.py         51     51     22      0     0%   2-85
iocage/cli/snapremove.py       31     31     10      0     0%   2-50
iocage/cli/snapshot.py         36     36     12      0     0%   2-58
iocage/cli/start.py            66     66     34      0     0%   2-106
iocage/cli/stop.py             60     60     28      0     0%   2-94
iocage/cli/update.py           46     46     22      0     0%   2-71
iocage/cli/upgrade.py          70     70     32      0     0%   2-121
iocage/lib/__init__.py          0      0      0      0   100%
iocage/lib/ioc_check.py        32     23     16      0    19%   15-21, 28-61
iocage/lib/ioc_clean.py        69     56     24      0    14%   16-18, 23-30, 34-71, 75-81, 85-117
iocage/lib/ioc_common.py      104     88     42      0    11%   13-32, 40-74, 80-103, 123-134, 158-169, 174-176, 181-186, 191-193
iocage/lib/ioc_create.py      170    151     60      0     8%   23-38, 46-173, 180-303, 310-362, 369-409, 413-431
iocage/lib/ioc_destroy.py      40     31      2      0    21%   16-25, 29-37, 41-61, 65-69
iocage/lib/ioc_exec.py         45     36     16      0    15%   16-24, 28-72
iocage/lib/ioc_fetch.py       514    475    232      0     5%   34-66, 71-90, 98-127, 131-175, 186-292, 304-343, 350-364, 371-452, 456-543, 549-559, 564-624, 628-770, 774-808, 817-836, 842-857, 864-877
iocage/lib/ioc_fstab.py        50     50     14      0     0%   2-88
iocage/lib/ioc_json.py        391    368    152      0     4%   15-18, 28-33, 37-53, 57-105, 109-205, 209-210, 215-307, 312-397, 403-404, 411-472, 479-669, 673-681, 684-713, 717-772
iocage/lib/ioc_list.py        135    123     66      0     6%   22-28, 33-112, 116-198, 202-217, 222-227
iocage/lib/ioc_start.py       226    210     68      0     5%   22-35, 48-291, 296-380, 384-387, 390-401, 409-438
iocage/lib/ioc_stop.py         89     81     40      0     6%   14-27, 30-165
iocage/main.py                 66     66     30      0     0%   2-98
-----------------------------------------------------------------------
TOTAL                        3178   2992   1254      0     4%


====================================================================== FAILURES ======================================================================
_____________________________________________________________________ PEP8-check _____________________________________________________________________
/usr/home/loic/iocage.git/iocage/cli/stop.py:45:69: E202 whitespace before ')'
                                    key=itemgetter(1), reverse=True) )
                                                                    ^

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================== 1 failed, 26 passed in 1.99 seconds =========================================================
```

Of course the behavior of the pep8 checker can be fine tuned, to ignore some errors/warnings.

Is there something you would like to see modified in this PR? Please check if the package build works flawlessly.

Cheers

### CODE REVIEW

**Comment by skarekrow** [comment]
You rock! This contribution looks great. Although `pytest` doesn't seem to like it?

```
╰─ pytest --version
usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --pep8 --cov-report --cov=iocage iocage iocage/tests
  inifile: /usr/home/bschneider/liocage/setup.cfg
  rootdir: /usr/home/bschneider/liocage
```

**Comment by lpefferkorn** [comment]
I forgot to mention that you have to install ```pytest-cov``` and ```pytest-pep8```. I guess this is a good time to start writing a ```requirements.txt``` maybe?

**Comment by skarekrow** [comment]
D'oh! Perhaps, I was naive and expecting `pip` to do that for me :D

**Comment by lpefferkorn** [comment]
Just noticed that test dependencies can be installed by running ``` python setup.py test```. I have updated the setup.py and README.md accordingly
If you want I can push setuptools integration with pytest a little bit further with the ```pytest-runner``` plugin.
It will be possible to install test dependencies and start tests using one command:
```
$ python setup.py test
```

Since this is an extra dependency, this is up to you :)

**Comment by skarekrow** [comment]
I think that's a useful dependency in this case, that way we have one consistent method to point users at when they ask how to run tests.

Will try this shortly!

**Comment by skarekrow** [comment]
So `python setup.py test` did not install the dependencies for me oddly. But that wasn't a big deal. Everything seems to work fine! I will have to blacklist `E203` :D But it seems some odd formatting snuck it's way past me.

**Comment by lpefferkorn** [comment]
I will update the PR with ```pytest-runner``` tonight. To add exceptions to the pep8 checker you just have to append to setup.cfg:
```
pep8ignore = E203
```
I am also learning how setuptools/pytest/pip work together :)

**Comment by skarekrow** [comment]
Yep I found that just now, turns out I have a lot of pep8 issues, damn you Pycharm! Will have to have a thorough OCD pep8 cleansing once this is merged :D

**Comment by lpefferkorn** [comment]
Maybe we can start with pep8 explicitly disabled in setup.cfg, then fix the pep8 issues in another PR?

**Comment by skarekrow** [comment]
Sure that sounds reasonable, it's better to get the testing stuff in before I pet my OCD with these pep8 issues.

**Comment by lpefferkorn** [comment]
After checking what can be done after ```pytest-runner```, I only end up with something more complicated that the actual solution.

 ```pytest --zpool=tank0``` for running functional tests where options have to be specified will look like ```python setup.py test --addopt --zpool tank0```

Not a huge win. What do you think? I would say merging this one if it suits you and continue in another PR for further modifications.

I have also updated the ```setup.cfg``` to ignore for now the pep8 issues.

**Comment by skarekrow** [comment]
Yeah somehow I think that's more difficult. I agree, I'll merge this and we can tackle that in a different PR.

**Pull request merged**
