### PR TITLE
Allow enabling per-jail SYSV IPC namespaces in FreeBSD 11

### PR DESCRIPTION
**Pull request by asomers**
Make sure to follow and check these boxes before submitting a PR! Thank you.
- [x] Supply documentation according to [CONTRIBUTING.md](https://github.com/iocage/iocage/blob/master/CONTRIBUTING.md)
- [x] Explain the feature
- [x] Read [CONTRIBUTING.md](https://github.com/iocage/iocage/blob/master/CONTRIBUTING.md)
- [ ] Only open the PR against the `develop` branch.

In FreeBSD 11.0 and later, SYSV message, semaphore, and shared memory
primitives can have per-jail namespaces.  This is controlled by the
"sysvshm", "sysvmsg", and "sysvsem" jail properties.  This commit adds
support for those properties to iocage.  The default is to disable sysv
IPC in jails.

Alternatively, I think it would acceptable for iocage to always set those properties to "new", enabling the per-jail namespaces.  I think that would be acceptable for almost everyone.  I can't think of any good reasons why you would want anything else.

### CODE REVIEW

**Comment by skarekrow** [comment]
Looks great! Can you open one against `develop` as well? This should be in both. I'll merge both of those PR's when that's done.

Thanks!

**Comment by asomers** [comment]
Yeah, I can do that.  I didn't realize that develop was still maintained.  I thought that it was abandoned in favor of the go-based iocage-ng.

**Comment by skarekrow** [comment]
Yeah it essentially is, but there may be users of it, so I want to make sure at the very least, it isn't some weird hybrid.

**Comment by skarekrow** [comment]
I commented on the `develop` PR, and I think the same thing can apply here. Instead of adding the function `__get_sysv_prop()` we can just make the if statements checking for the kernel version set them to `new` in an else statement instead.

**Comment by asomers** [comment]
@skarekrow that would set those properties to "new" unconditionally when using recent kernels.  `__get_sysv_prop()`, or something like it, is still necessary if you want the properties to be settable, as they probably should be.  And bear in mind that iocage needs to handle the case where that property isn't even set on the dataset.  That would happen if the user created a jail with an older version of iocage and then upgraded to this version.

**Comment by skarekrow** [comment]
Yeah you're right, we should leave this one alone. I'll keep thinking on the develop issue. I wish I versioned the configuration files...

**Comment by skarekrow** [comment]
Thanks again 👍

**Pull request merged**
