### PR TITLE
For review only -- DO NOT MERGE

### PR DESCRIPTION
**Pull request by grobe0ba**
This branch presents a massive overhaul in the usage of quotes and braces, and in some case reliance on fickle shell globbing, along with several other less than opportune things. It basically boils down to: All variables will be in double quotes and braces (e.g. "${var}") except in circumstances where that is contraindicated. All command substitutions shall be in double quotes to prevent globbing. Among the circumstances where this is not desirable are the replies from __get_jail_prop and some places that require an unquoted return to allow globbing where needed. This pull request should not be merged as-is. Instead, please make contact with me so I can merge it in my upstream system external to GitHub and re-submit a pull request. Testing of some features has been performed on my 9.3 box (non-VNET only) and my 11-CURRENT r281393M box (non-VNET and VNET), but should not by any means be considered adequate testing.

### CODE REVIEW

**Comment by pannon** [comment]
Thanks @grobe0ba, I did have a quick look at most of the changes in this PR. This is a significant change as you already stated. Going forward with these has the potential to brake things in some very subtle ways.

I agree with you on maintaining a standardized coding style and principles but on the other hand I believe we have a choice to make these changes gradually - one step at the time with low risk.

If we want to make these principles maintainable going forward we also need to think about future commiters and set of rules, maybe create a doc page on how to contribute to iocage and what the expectations are. We also don't want to scare folks away from contributing by enforcing too much on them.

Currently we are pretty lean on manpower and testing would be inadequate and this is at a time when iocage is gaining some momentum - we should leverage this momentum to make the user experience as smooth as possible and polish things where needed most.

So my thoughts wrapped up in a nutshell:
- we should all agree on basic guidelines
- create a doc/framework on how to make this work
- let's introduce changes gradually
- spend our limited resources at this moment on getting the user experience right

**Comment by pr1ntf** [comment]
I think that is a great idea, @pannon. I've also been wondering if there is some sort of TODO list you and @skarekrow have in mind as well.

**Comment by pannon** [comment]
For the TODO items we could just leverage GH issues and just put the "FEATURE" keyword in the subject field. So for each planned feature or enhancement create an issue and assign to the person who has interest in it.

Maybe a good time to create some branches too like release, stable and leave master for bleeding edge?

cc: @skarekrow

**Comment by grobe0ba** [comment]
I think I actually managed to catch most if not all of the subtle breakage points. While this is a really big diff, in 99% of the changes the operation of the code hasn't changed.

I personally have always been prone to pushing massive changes all at once, and I can see from where you're sitting how that could be a massive issue. I totally agree that we need something for people to reference. 

I also strongly believe that this is a really _big_ issue, not merely a minor one, that for now, needs to come before feature additions. New features are important, but the more you grow the code without fixing this or adhering to a set of guidelines, the harder it'll be if you ever decide to actually do it, and less likely that you ever will. I agree with @pannon that splitting into master/stable/release branches is a good thing to do right now. We have a solid working code base to go from, that runs on the predominant versions of FreeBSD.

Perhaps instead of merging one giant commit, breaking this diff apart into multiple commits a section at a time is the way to do this. That allow for testing, and allows this to be done _now_, before everything is too set in stone.

Fortune favours the bold. Lets make iocage the gold standard of jail management.

**Comment by pr1ntf** [comment]
I was going to suggest that, possibly going function by function. 

Also, I do like the feature request idea.

**Comment by pannon** [comment]
The function by function sounds great. I also had a thought for easier development and change introduction - split functions out into separate files (libraries) by groups like ZFS, rctl, jail etc. and source them in the main script (not a new idea). I was resisting this before as the script was relatively small.

This way we could add non intrusively support for a lot more stuff and maintain things easier.

Also the code is growing and this would ease the testing/maintenance/commits.

Any thoughts?

@skarekrow @pr1ntf @dlangille @grobe0ba

**Comment by grobe0ba** [comment]
I like it. Having everything in one script is kind of cluttered already. (Random vaguely tangential idea: That would add the possibility of a sort-of module system for people to roll-their-own additions.)

**Comment by skarekrow** [comment]
Well I did suggest doing the split @pannon ;) But that also takes a lot of effort for another cosmetic thing at this point in time. I also think we should start to do branches, so we can experiment more in the master branch. Possibly just having a master/develop branch and tagging releases as we go. I'm not sure if this particular PR is as big of a deal as you are saying @grobe0ba. I do agree that consistency is best and having a document makes contribution better, but this in my opinion is not better then new features.

New features and bug fixes enhance the user experience. Changing our scripts formatting does not. While it is a nice to have feature to make sure everything is consistent, that's something that many users wouldn't notice. It just would take a significant amount of time to test everything that changed. A great example would be your recent PR for fixing the 9.3-RELEASE hosts using iocage. That broke in many ways and that was only one small feature. You are proposing a change that touches the entirety of iocage. I do not believe this is of priority, but that is just my opinion.

I personally feel it is better to split the script and make everything cohesive at the same time rather then do it now, and then also split it later. Not to mention we have a lot of other things that need to be done.

**Comment by grobe0ba** [comment]
That's the thing. Its a formatting thing second, and a reliability and quality thing first. Not quoting variables is a quick path to problems. There are at least two places in master right now where you're relying on side effects of variable assignment to do things they shouldn't. I wouldn't have spent three days building this just to make it pretty. As for breaking lots of things, I'll own up to that, but this is only major in line count, not functionality. For that matter, if we split everything into separate files, we can then apply it in sections to those, achieving twice as much with the same amount of work.

**Comment by dlangille** [comment]
+1 for splitting.

**Comment by pr1ntf** [comment]
Let's split. 
I mean, this is a FreeBSD program. It's nice to fetch a script, but make(1) is on every FreeBSD machine anyway.

**Comment by skarekrow** [comment]
I did not mean to discredit the work you've done as just prettifying things up. But I have some questions about this PR. Beyond the insane level of testing that will be required. I would much rather fix what's broken now and then continue this once that is done. You mentioned there are atleast two places in master, would you mind telling me the line numbers? You also have some things I"m not sure about. You are double quoting on line 503, is that necessary?

@pr1ntf Yes, I don't think the intention was for easy fetching via fetch or anything. I think we intend users to use pkg or build from ports. So having a makefile wouldn't be the end of the world. I proposed splitting to Peter a couple times over the last couple months and we both agree it should be the path we move down. But time is the issue and testing those changes is another. It is a radical departure for the script.

**Comment by grobe0ba** [comment]
I'm sure there are a few places I messed up in it. As has been pointed out, it's a really big diff. As for the places in master that are buggered, I'll submit a pull request on those here in a little bit. I just got back from dinner.

**Comment by grobe0ba** [comment]
Also, on 503 if you are referring to:
local fulluuid="$(__check_name "${name}")"
Then yes, that is necessary. The outside quotes only deal with the return from the command substitution, the inner ones prevent distortion of the variable substitution which affects the input to the function.

**Comment by skarekrow** [comment]
Alright. Thanks for elaborating on that. Also I'm looking forward to that PR. In the meantime, just know i'm not trying to attack you or your work. You know my stance on this, I am against something like this for the time being until we start splitting the script. I just did a small quick test of this pull and it breaks basejails. That is just a rabbit hole not worth going down right now. I will be applying my energy elsewhere.

**Comment by grobe0ba** [comment]
I'm gonna bash on the basejail thing real quick. It's probably a really cheesy little mistake that broke it.

**Comment by pannon** [comment]
@grobe0ba please can you explain the "*distortion of the variable substitution*" issue?

I am unaware of what that means or what the consequences are if we leave line 503 only between one set of quotes.

**Comment by grobe0ba** [comment]
local fulluuid=$(__check_name ${name})

Say name is equal to... Byron Grobe
If ${name} isn't double quoted, __check_name receives two arguments, Byron and Grobe. Eventually, someone is going to try to put spaces in things, and it'll be painful to figure out exactly what is going wrong inside the script if it's in a place where that could be desirable.

Essentially the same thing happens if __check_name for some reason returns, say, NAME EXISTS as a string. You'll end up getting NAME assigned to the variable, but the EXISTS can get lost.

If you have only the outer quotes, your return value is safe, you know you're not losing things, but the data being sent to __check_name could be losing things off the end.

If the user decided at some point to set IFS (external to iocage) to something like a tack (-), you could end up dropping off everything paste the first tack in the UUID.

That's why quoting of variable and command substitution is important. You get unexpected results on assignments and argument passing. Right now, you're leaving it up to the shell to figure out exactly what data gets passed and in what form. Being explicit means you _know_ what you're getting each and every time.

**Comment by skarekrow** [comment]
Ah, that is very nice. Thanks @grobe0ba.  I hadn't thought about someone setting a different IFS outside the script. Couldn't we just explicitly define a IFS in our script? I thought it was assumed to be by default a space.

**Comment by pannon** [comment]
OK, thanks for that @grobe0ba . I think this cleanup is best to leave for the same time when we split things out.

So let's increment iocage version tag it and create a development branch where we can start splitting.

**Comment by skarekrow** [comment]
:+1:

**Comment by grobe0ba** [comment]
@skarekrow, it's generally safe to assume that IFS is a space, and yes, you could work around it by forcibly setting it to something else. However, it is in my opinion _very_ unwise to consider that a fix. A stopgap measure until everything can be cleaned up, definitely a viable option.

I'm not trying to push to get this merged in right this second, I just want to make sure everyone is aware of the issues that can be caused.

@pannon, that sounds good to me. Getting everything split, and then code cleaning after is a good plan.

P.S. I also did this as one big commit just to cause peoples' brains to go BOOM! :D

**Comment by skarekrow** [comment]
Sounds good to me. That's all I was suggesting @grobe0ba was to do this once we started the split. I was under the assumption you wanted it merged before that.

**Comment by pr1ntf** [comment]
Mission accomplished. :p Good chat y'all.

**Comment by grobe0ba** [comment]
My bad, mates. I'm not so good with the communicating with other people.

As for merging before, I still think it has benefits, once I fix the basejails (which is probably a trivial fix). That way we could combine a code cleanup with the split, and debug it all at once.

There are pros and cons doing it either way, and its your project, not mine.

**Comment by pannon** [comment]
I am OK with either way but lets put the "fixed" up version into devel branch and we can merge when fully ready.

**Comment by skarekrow** [comment]
It could be a trivial fix, it could also be a tremendous amount of linting to find. Personally I think doing these changes as we split will allow us to make sure each function functions before we move on to correcting the next one. That way we aren't debugging it all at once. But incrementally. Much easier to manage.

**Comment by skarekrow** [comment]
I agree, if you can reopen this against develop @grobe0ba we can merge and then commence work on splitting.

**Comment by grobe0ba** [comment]
True. I'll bet that I have basejails fixed in the next half hour. It's not nearly as much linting as you'd think.

**Comment by skarekrow** [comment]
I'll hold you to that ;)

**Comment by grobe0ba** [comment]
Fixed it. Gotta push and whatnot, but it's fixed. I misplaces four total doublequotes.
Told you it was trivial.

**Comment by skarekrow** [comment]
:) That's good. Include those fixes in the PR to the dev branch and we can start hacking at splitting this beast up.

**Pull request closed without merging**
