### PR TITLE
support allow_mount_linprocfs

### PR DESCRIPTION
**Pull request by hxw**
needs so nested jails can use linprocfs
e.g., for poudriere in a jail

Signed-off-by: Christopher Hall <hsw@ms2.hinet.net>

Make sure to follow and check these boxes before submitting a PR! Thank you.

- [X] Explain the feature
- [X] Read [CONTRIBUTING.md](https://github.com/iocage/iocage/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by hxw** [comment]
I have attempted to rebase my changes on the latest master
after the previous pull request failed.
Pleas let me know if I need to retry my rebase.

**Comment by skarekrow** [comment]
LGTM, @sonicaj you?

**Review by dgeo — APPROVED** [review]
tested and approved :)

**Comment by sahlawat** [comment]
This commit is a breaking change; it maybe better to revert this till all the workflows are addressed.
The allow_mount_linprocfs property is not treated as optional.
Existing jail config.json files need to be edited to add this property for them to start.
Also iocage create does not add this property to config.json so newly created jails cannot be started;  workaround is to include allow_mount_linprocfs on the create command-line

**Pull request merged**
