### PR TITLE
add start behaviour to boot property in iocage(8)

### PR DESCRIPTION
**Pull request by Corvan**
This relates to #1023 
Make sure to follow and check these boxes before submitting a PR! Thank you.

- [x] Explain the feature
- [x] Read [CONTRIBUTING.md](https://github.com/iocage/iocage/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by skarekrow — COMMENTED** [review]
Thanks! Don’t forget the gzip as well.

**Comment by Corvan** [comment]
oh, sorry

**Review by skarekrow — APPROVED** [review]
LGTM @sonicaj?

**Review by sonicaj — APPROVED** [review]

**Comment by Corvan** [comment]
thx

**Pull request merged**
