### PR TITLE
Add ability to fetch from a custom directory using ftplocaldir, add c…

### PR DESCRIPTION
**Pull request by net-error**
…leanup when fetch fails, add doc info

### CODE REVIEW

**Comment by skarekrow** [comment]
Hello :)

If you could adjust `__cleanup_release_dir` to accept a variable instead of using the global `$release` that would be helpful.

Currently fetch doesn't use it, as the variables aren't exported yet, so it uses `_release`. Which I also suggest you use for `__cleanup_release_dir`

So then when the fetch fails you can could then call `__cleanup_release_dir ${_release}`. Could you also please send the failed fetching text to stderr as well? Like the echo that it is replacing.

Last thing, you don't want to edit `iocage.8.txt` on it's own. You want to edit lib/ioc-help and run the command that `CONTRIBUTING.md` shows.

Thanks for the PR otherwise!

**Comment by net-error** [comment]
Will, do...Thanks for the advice

**Comment by net-error** [comment]
Done .......YAY me.

**Comment by skarekrow** [comment]
Fantastic, thanks for squashing your commits as well :) Will test this out next week, holidays here ;)

Thanks again for the PR.

**Comment by skarekrow** [comment]
Oh just noticed you have the gzip file included, make sure to remove that heh

**Comment by skarekrow** [comment]
Thanks!

**Pull request merged**
