### PR TITLE
update help output to make two examples clearer

### PR DESCRIPTION
**Pull request by cactus**
Looks like the help output was missing a left bracket, and made the snapshot vs ALL param a bit clearer.

### CODE REVIEW

**Comment by skarekrow** [comment]
Thanks!

**Comment by cactus** [comment]
@skarekrow I saw the missing `[` and supplied it, but wasn't sure if it was intended to be labeled as optional or not. Does it make sense as it is in the pull as merged, or would you prefer a subsequent pull req to make them look like this:

```
iocage get property|all UUID|TAG
iocage snapremove UUID|TAG@snapshotname|ALL
```

**Comment by skarekrow** [comment]
@cactus looks fine to me as is.

@pannon any thoughts?

**Comment by pannon** [comment]
@skarekrow sweet. cc: @cactus

**Comment by cactus** [comment]
Here is an alternative, with updated readme and manpage too.

https://github.com/iocage/iocage/compare/develop...cactus:develop

I tried regenerating the cat page with `man ./iocage.8 | col -bx > iocage.8.txt` but the diff was huge -- looks like different prefix spacing...so I didn't include that.

Let me know if you want this as it stands, or would prefer the additional pull req.

**Comment by skarekrow** [comment]
@cactus That actually looks better. Please PR that, and we can do the manpage no worries. Otherwise if you want we use ```txt2man```.

```iocage help | txt2man -t iocage -s 8 -v "FreeBSD System Manager's Manual" > iocage.8```

And it will generate the man for you.

Then you can regenerate the text file with ```iocage help > iocage.8.txt```

**Comment by cactus** [comment]
Sounds good. Opened new pull req. #128

**Pull request merged**
