### PR TITLE
Quietly start jail if needed when running 'iocage exec'

### LINKED ISSUE #668: Running 'iocage exec' when jail is down
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

On iocage master, when running `iocage exec`, the command fails when the jail is not running.
```
➜  ~ sudo iocage exec foo cat /etc/motd
jexec: jail "ioc-foo" not found
Command failed!
Exception: "CommandFailed:Command: ('cat', '/etc/motd'), stdout: None, stderr: None" occured
```
If I remember correctly, I think it used to automatically start the jail.  Was that done on purpose, or is that a regression?

### PR DESCRIPTION
**Pull request by jsegaert**
Make sure to follow and check these boxes before submitting a PR! Thank you.

- [X] Explain the feature
- [X] Read [CONTRIBUTING.md](https://github.com/iocage/iocage/blob/master/CONTRIBUTING.md)

This fixes #668

### CODE REVIEW

**Review by skarekrow — COMMENTED** [review]
Are we sure this is only needed for interactive commands?

**Review by gronke — CHANGES_REQUESTED** [review]
This behavior matches with libiocage `exec --fork`. 👍😍 

I'd love to see the `-f/--fork` option added, so that the CLI commands use a common syntax.

**Comment by jsegaert** [comment]
Great question.  Correct; only the interactive commands are not covered.  Similar logic already exists for "pkg" and "console" and the IOCExec generator does it in the "flight_checks".

Note that because of the latter, some commands such as `iocage get -P` require root privileges because they may attempt to start the jail (and would need it to run jexec anyway).

**Comment by skarekrow** [comment]
@gronke That doesn't make sense, these commands aren't forking. They're starting a jail that isn't running so the command can be run. That's a separate PR if we want to add that to v1. The user could do it manually by adding `&` to their command and the jail would return immediately anyways.

**Review by skarekrow — APPROVED** [review]

**Pull request merged**
