### PR TITLE
tkt-74020: Remove unprotected devfs_rulesets

### PR DESCRIPTION
**Pull request by skarekrow**
This conditional was incorrect after recent changes to grabbing the dynamic ruleset

FreeNAS Ticket: #74020

### CODE REVIEW

**Review by themylogin — DISMISSED** [review]

**Review by sonicaj — COMMENTED** [review]
I think there is potential for error as int(devfs) can fail as strings are allowed as well here

**Comment by skarekrow** [comment]
> I think there is potential for error as int(devfs) can fail as strings are allowed as well here

How so? They're always ints

**Comment by sonicaj** [comment]
`
root@freebsd12vm:~ # iocage set devfs_ruleset=asdf foo
devfs_ruleset: 4 -> asdf
root@freebsd12vm:~ #
`

**Comment by sonicaj** [comment]
Oops, sorry. Messed up the indentation. The root cause is different here though as i think we should validate that prop ? Thoughts ?

**Comment by skarekrow** [comment]
Different problem, this will be grabbing the ruleset from `jls`, but that is absolutely a good candidate for validation.

**Review by sonicaj — DISMISSED** [review]

**Review by sonicaj — APPROVED** [review]

**Pull request merged**
