### PR TITLE
NAS-102750 / 11.3 / Update basejails configuration correctly

### PR DESCRIPTION
**Pull request by sonicaj**
This commit makes sure we update basejails configuration correctly. If a basejail is not running, freebsd-version file will be non-existent and that would result in a corrupt configuration for the basejail in question as it won't be updated.

### CODE REVIEW

**Review by skarekrow — COMMENTED** [review]
Why not use the jails RELEASE prop?

**Comment by sonicaj** [comment]
The idea is to correct the value of RELEASE prop ;)

**Comment by sonicaj** [comment]
In our earlier versions, we had a few bugs which resulted in misconfigured release property, so we introduced these checks to ensure that each time a config is updated, RELEASE prop reflects the correct release version.

**Comment by skarekrow** [comment]
Whoops forgot that! Haha

**Review by skarekrow — APPROVED** [review]

**Pull request merged**
