### PR TITLE
NAS-104039 / 11.3 / Make sure we don't error out listing jails if a jail doesn't have roo…

### PR DESCRIPTION
**Pull request by sonicaj**
…t dataset

Make sure to follow and check these boxes before submitting a PR! Thank you.

- [ ] Explain the feature
- [ ] Read [CONTRIBUTING.md](https://github.com/iocage/iocage/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by skarekrow — COMMENTED** [review]
Would probably look nicer as a one liner?

**Comment by sonicaj** [comment]
80 characters line limit doesn't really make it a one liner :D

**Comment by skarekrow** [comment]
I meant ignoring that :D but sure it doesn’t matter

**Review by skarekrow — APPROVED** [review]

**Comment by sonicaj** [comment]
backport

**Comment by sonicaj** [comment]
Hahaha @skarekrow, i tried that way, but looked weird as a one liner continuing to the next line :p

**Pull request merged**
