### PR TITLE
Mentioning raw sockets in network docs

### PR DESCRIPTION
**Pull request by brejoc**
Make sure to follow and check these boxes before submitting a PR! Thank you.

- [x] Supply documentation according to [CONTRIBUTING.md](https://github.com/iocage/iocage/blob/master/CONTRIBUTING.md)
- [x] Explain the feature
- [x] Read [CONTRIBUTING.md](https://github.com/iocage/iocage/blob/master/CONTRIBUTING.md)
- [x] Only open the PR against the `develop` branch.

New users are very likely not aware of the allow_raw_sockets option
and might think that the network setup of their Jail is broken, when
a simple ping and pkg update is not working, even though only this
option needs to be set.

### CODE REVIEW

**Comment by skarekrow** [comment]
While I do like this addition, it is not necessary to use raw sockets to use `pkg` in a jail.

Example:
```
 bschneider@ansible-client  ~  iocage get allow_raw_sockets test
0
 bschneider@ansible-client  ~  sudo iocage start test
* Starting ec1d7f37-2c3b-11e6-bd16-efcda6a55858 (test)
  + Started (shared IP mode) OK
  + Starting services        OK
 bschneider@ansible-client  ~  iocage get allow_raw_sockets test
0
 bschneider@ansible-client  ~  sudo iocage console test
FreeBSD 11.0-CURRENTMAY2016 (GENERIC) #19 5bab0d2(master): Fri May  6 17:56:25 UTC 2016

Welcome to FreeBSD!

Release Notes, Errata: https://www.FreeBSD.org/releases/
Security Advisories:   https://www.FreeBSD.org/security/
FreeBSD Handbook:      https://www.FreeBSD.org/handbook/
FreeBSD FAQ:           https://www.FreeBSD.org/faq/
Questions List: https://lists.FreeBSD.org/mailman/listinfo/freebsd-questions/
FreeBSD Forums:        https://forums.FreeBSD.org/

Documents installed with the system are in the /usr/local/share/doc/freebsd/
directory, or can be installed later with:  pkg install en-freebsd-doc
For other languages, replace "en" with a language code like de or fr.

Show the version of FreeBSD installed:  freebsd-version ; uname -a
Please include that output and any error messages when posting questions.
Introduction to manual pages:  man man
FreeBSD directory layout:      man hier

Edit /etc/motd to change this login announcement.
root@ec1d7f37-2c3b-11e6-bd16-efcda6a55858:~ # ping www.google.com
ping: socket: Operation not permitted
root@ec1d7f37-2c3b-11e6-bd16-efcda6a55858:~ # ping 8.8.8.8
ping: socket: Operation not permitted
root@ec1d7f37-2c3b-11e6-bd16-efcda6a55858:~ # pkg update
The package management tool is not yet installed on your system.
Do you want to fetch and install it now? [y/N]: y
Bootstrapping pkg from pkg+http://pkg.FreeBSD.org/FreeBSD:10:amd64/quarterly, please wait...
Verifying signature with trusted certificate pkg.freebsd.org.2013102301... done
[ec1d7f37-2c3b-11e6-bd16-efcda6a55858] Installing pkg-1.7.2...
[ec1d7f37-2c3b-11e6-bd16-efcda6a55858] Extracting pkg-1.7.2: 100%
Updating FreeBSD repository catalogue...
[ec1d7f37-2c3b-11e6-bd16-efcda6a55858] Fetching meta.txz: 100%    944 B   0.9kB/s    00:01
[ec1d7f37-2c3b-11e6-bd16-efcda6a55858] Fetching packagesite.txz:  22%    1 MiB  [ec1d7f37-2c3b-11e6-bd16-efcda6a55858] Fetching packagesite.txz:  37%    2 MiB 8[ec1d7f37-2c3b-11e6-bd16-efcda6a55858] Fetching packagesite.txz:  62%    3 MiB  [ec1d7f37-2c3b-11e6-bd16-efcda6a55858] Fetching packagesite.txz:  86%    5 MiB  [ec1d7f37-2c3b-11e6-bd16-efcda6a55858] Fetching packagesite.txz: 100%    5 MiB   1.4MB/s    00:04
Processing entries: 100%
FreeBSD repository update completed. 25086 packages processed.
root@ec1d7f37-2c3b-11e6-bd16-efcda6a55858:~ # pkg
pkg: not enough arguments
Usage: pkg [-v] [-d] [-l] [-N] [-j <jail name or id>|-c <chroot path>|-r <rootdir>] [-C <configuration file>] [-R <repo config dir>] [-o var=value] [-4|-6] <command> [<args>]

For more information on available commands and options see 'pkg help'.
root@ec1d7f37-2c3b-11e6-bd16-efcda6a55858:~ #
```

**Comment by brejoc** [comment]
You are right. I could have sworn `pkg update` didn't work. I'll change it accordingly.

**Comment by skarekrow** [comment]
👍 Thanks for the PR though. I could definitely see a new user getting tripped up on this.

**Comment by brejoc** [comment]
@skarekrow I've removed the part about pkg. Let me know if something else is missing or wrong.

**Comment by skarekrow** [comment]
Looks great, can you squash those 2 commits into one and I'll merge.

**Comment by skarekrow** [comment]
Nvm! Github now allows me to do it much faster. Thanks for the PR!

**Comment by brejoc** [comment]
👍

**Pull request merged**
