### PR TITLE
Improve the "iocage fstab" example.

### PR DESCRIPTION
**Pull request by asomers**
This documents by example what the fstab format should look like.

### CODE REVIEW

**Review by nathanjrobertson — CHANGES_REQUESTED** [review]
You'll need to fix the conflict in the date at the top of the file. The actual documentation update is good though - the man page confused me for fstab when I read it because it lacked your update.

**Comment by asomers** [comment]
@nathanjrobertson is it good now?

**Review by nathanjrobertson — DISMISSED** [review]
Looks good. Makes the example much clearer and more useful.

@sonicaj Please consider merging this patch.

**Comment by skarekrow** [comment]
Perhaps adding this as an additional example in addition to the edit one? This will also need a gzip'd file along with the edit.

**Comment by asomers** [comment]
Added a compressed man page

**Review by sonicaj — APPROVED** [review]
LGTM. Thank you @asomers. @skarekrow would you like to have a peek again ?

**Review by skarekrow — APPROVED** [review]

**Comment by asomers** [comment]
The test failure looks like an intermittent network issue.  Could somebody please restart it?

**Comment by skarekrow** [comment]
Sorry about that! Some git-fu backfired, can you please reopen this? Thanks!

**Pull request closed without merging**
