### PR TITLE
.gitignore: first introduction

### PR DESCRIPTION
**Pull request by moviuro**
Ignore the *.gz files (documentation)

### CODE REVIEW

**Comment by skarekrow** [comment]
This isn't actually necessary as the makefile deletes the .gz files. What ones are you trying to ignore?

**Comment by moviuro** [comment]
@skarekrow Hi, well, when I run
```
# make install
```
The `.gz` file is generated if needed but it stays in place once it's done. Perhaps I'm missing something?

**Comment by skarekrow** [comment]
Hello :) 

Yes, run `make install clean` as root.

**Comment by moviuro** [comment]
Meh, I should really learn about `make` and `MakeFile`... Excuse the n00b :wink:

**Comment by skarekrow** [comment]
:D No problem!

**Pull request closed without merging**
