### PR TITLE
Improve exception handling when renaming jails

### PR DESCRIPTION
**Pull request by jsegaert**
Make sure to follow and check these boxes before submitting a PR! Thank you.

- [X] Explain the feature
This is a follow up on my PR from the other day.  Main improvements are:
- Proper handling of situations when no fstab file exists
- Will now force unmount when calling rename() in libzfs.  This addresses the occasional "libzfs.ZFSException: Device busy" errors when renaming jails.  I noticed this happened almost always when renaming plugins and is also described in issue #431 
- [x] Read [CONTRIBUTING.md](https://github.com/iocage/iocage/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by skarekrow — APPROVED** [review]
Looks good, thanks!

**Comment by berenddeboer** [comment]
Still happens here:

````
# iocage --version
Version	1.0 ALPHA

# iocage stop new-unifi
* Stopping new-unifi
  + Running prestop OK
  + Stopping services OK
  + Tearing down VNET OK
  + Removing jail process OK
  + Running poststop OK

# iocage rename new-unifi unifi
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/rename.py", line 39, in cli
    ioc.IOCage(exit_on_error=True, jail=jail).rename(new_name)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1241, in rename
    self.zfs.get_dataset(path).rename(new_path)
  File "libzfs.pyx", line 2215, in libzfs.ZFSObject.rename
libzfs.ZFSException: Device busy

# iocage list
+-----+-------+-------+--------------+------+
| JID | NAME  | STATE |   RELEASE    | IP4  |
+=====+=======+=======+==============+======+
+-----+-------+-------+--------------+------+
| -   | unifi | down  | 11.1-RELEASE | DHCP |
+-----+-------+-------+--------------+------+
````

So only does partial rename, leaving me in a stuck state.

I cannot start the new name, but can start the old one:

````
# iocage start new-unifi
* Starting new-unifi
  + Started OK
  + Configuring VNET OK
  + DHCP Address: 192.168.33.12/24
  + Starting services OK
````

**Comment by berenddeboer** [comment]
The reason is this I suspect:

````
# zfs umount home/iocage/jails/new-unifi/root
cannot unmount '/mnt/home/iocage/jails/new-unifi/root': Device busy
````

what iocage should do is update `config.json` to `config.json.new` and only when the zfs rename completes update `config.json`.

**Comment by berenddeboer** [comment]
The solution seems to wait a bit? Not sure, after some minutes I could umount, then the rename proceeded smoothly.

**Comment by jsegaert** [comment]
The Traceback shows you're still running the version that doesn't have the patch.

**Pull request merged**
