### PR TITLE
GitHub actions for tests

### PR DESCRIPTION
**Pull request by fulder**
Minor flake/unit tests refactoring and CI change. Main PR changes:

* Move travis flake8 job to github actions
* Run github action tests for python 3.6. 3.7, 3.8 and 3.9 versions
* Move test dependencies to own `requirements-test.txt` file
* Move `libzfs` dependencies/imports to functional test fixtures. This way it gets easier to run only the unit tests on a dev. machine (without the FreeBSD system requirement).
* Run functional tests in cirrus ci only
* Run unit tests in github actions (this gives much faster feedback compared to having to wait for all functional tests to pass)
* Upload coverage to coveralls.io. Report example: https://coveralls.io/builds/38911561

**EDIT**: Can't see any actions has been triggered after creating my PR (although it did work just fine on my fork: https://github.com/fulder/iocage/actions/runs/760670712), have they maybe been disabled (for some reason?) in this repo? :(

-----

Make sure to follow and check these boxes before submitting a PR! Thank you.

- [x] Explain the feature
- [x] Read [CONTRIBUTING.md](https://github.com/iocage/iocage/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by skarekrow** [comment]
This looks good to me, it seems to have a conflict. I see the Github actions on my end here, I don't believe I've disabled anything in the repo for those.

**Comment by igalic** [comment]
> This looks good to me, it seems to have a conflict. I see the Github actions on my end here, I don't believe I've disabled anything in the repo for those.

might still be good to only allow known good actions
https://mastodon.social/@cassidyjames/106099894241968588

**Comment by skarekrow** [comment]
> > This looks good to me, it seems to have a conflict. I see the Github actions on my end here, I don't believe I've disabled anything in the repo for those.
> 
> might still be good to only allow known good actions
> https://mastodon.social/@cassidyjames/106099894241968588

Woah good looking out! Thanks!

**Comment by fulder** [comment]
> This looks good to me, it seems to have a conflict. 

Thanks :) I have now merged in the latest upstream master and solved the conflicts. 

> I see the Github actions on my end here, I don't believe I've disabled anything in the repo for those.

That's a bit weird I still see the "required" Travis CI job (seems to be stuck forever in this state) in this PR 

image

and the github actions page is "blank" for me:
image

**Comment by fulder** [comment]
After thinking a bit about this and reading some docs this is probably a good limitation and protection against running workflows without the repository maintainers knowledge. It would be pretty dangerous if anyone could open up a PR to a public repository running e.g. a cryptominer, as @igalic mentioned, without any limitation.

Related github actions documentation: https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks. @skarekrow do you see this `Approve and run` button on your end? If so it could be the one making me not being able to see the new action and could be required to press, **of course** if everything with the action/PR looks fine.

**Comment by skarekrow** [comment]
@fulder no, I changed the settings to require it to be in the repo before they're allowed. I didn't see it before that either though, so I'm wondering if that button appears *after* we've added actions, since your PR is technically the first time.

**Review by skarekrow — APPROVED** [review]

**Comment by skarekrow** [comment]
Which didn't work how I expected 😂 

```
actions/checkout@v2 and actions/setup-python@v2 are not allowed to be used in iocage/iocage. Actions in this workflow must be: within a repository owned by iocage.
```
I changed some more things, we'll see next time that thing runs. It doesn't seem I can kick it off manually.

**Comment by skarekrow** [comment]
I see this trying to rerun it from the CLI:
```
gh run rerun 781280561
run 781280561 cannot be rerun; its workflow file may be broken.
```
I wonder if that also needs the `workflow_dispatch` event for being able to be reran. As I don't see the GUI button the docs show 🤷

**Comment by fulder** [comment]
> Which didn't work how I expected :joy:
`actions/checkout@v2 and actions/setup-python@v2 are not allowed to be used in iocage/iocage. Actions in this workflow must be: within a repository owned by iocage.
`
I changed some more things, we'll see next time that thing runs. It doesn't seem I can kick it off manually.

Could this be because you selected `Allow local actions only`? I interpret that (and the error message) as only actions defined in repos owned by the `iocage` github "user" can be used.

Thank you for the merge btw :) I just merged back master to another PR I have opened here, seems like it works just fine there now: https://github.com/iocage/iocage/pull/1250 :smile_cat:

**Comment by skarekrow** [comment]
Yeah I misinterpreted that as meaning only actions defined in our repo. AKA merged ones. But it seems they really meant local. Lol. Woot! I’ve been leaving the plugin stuff for @sonicaj as they’re the primary consumers of that. Hopefully he pops by.

Brandon

**Pull request merged**
