### PR TITLE
${iocroot} fix

### PR DESCRIPTION
**Pull request by sineer**

### CODE REVIEW

**Comment by sineer** [comment]
ioc-global ${iocroot} doesn't work because it is hardcoded to /iocage

This PR fix this by replacing every instance of /iocage by ${iocroot}.

Warning: Has yet to be fully tested! Also I did comment out some code in ioc-zfs delated to the altroot check and overwriting of the iocroot var in ioc-globals that I don't fully understand and doesn't work with thix fix...

**Comment by sineer** [comment]
Err, I'm confused and don't understand how find_jail was working previously... I fixed the grep to look for /jails/${_name} and it seems to work fine now..

I also tested with custom iocroot="/ioc" and it's working... more testing is required too and I suspect more things may be broken.

**Comment by sineer** [comment]
Err: if iocroot is two folders deep (i.e. iocroot=/my/iocage) it will break because of how we use "zfs list -d2 ..." the depth will break and find_jail() won't work...

I'm not sure how to fix that properly and don't have time to do it now :-(

**Comment by skarekrow** [comment]
I won't be merging this :) I actually changed how it was a while back. It used to function how you have this PR working. iocroot is now nothing more then where you have it mounted in the filesystem. Too many things rely on being under `POOL/iocage`. As you've noticed, it gets finicky, and that's discounting the recent changes with templates and altroot, which are more important.

So to clarify, setting iocroot ONLY changes where `POOL/iocage` is mounted in the filesystem. It does *not* change the datasets location within the pool.

Thanks for the effort though :)

**Comment by sineer** [comment]
It does get "finicky" indeed heh. a real pain to maintain indeed... and probably not worth it.

still I very much like to have control over this and also think it could be useful to have a "workflow" going where you'd have branches similar to how git branches work. I could see that especially useful right now given that cloning is broken... You could just zfs clone all jails into a new $iocroot and begin upgrading or testing whatever.. then fallback or delete old iocroot...

I often have a jail for sql, a jail for www another jail for some java process and so on. I setup fixed IP address and custom port redirection rules... It would be nice to be able to zfs clone them all into a new branch I can go in and experiment without having to worry about snapshots. Put aside experiments and go back to stable iocroot then go back experiment some more until I get it right. Better yet I could have both running side by side by simply switching the $iocroot in one shell.

**Comment by skarekrow** [comment]
And if the user changes the iocroot of the current running jails? That would cause the root of the jails to move underneath them. This would also require having fetched RELEASEs in each iocroot as well. I can see the merit, but it sounds like a tremendous amount of work for a possibly niche feature. Feel free to keep working on it, and if something cool materializes and works then I will reopen this. But it has to work with all the changes. I won't be removing altroot or the new templates for 2.0. And there are still things that need to be done.

The other major issue is that cloning with the new basejails is broken. It causes the host to segfault, and that would mean all this work wouldn't even result in a functioning system :(. That's being looked into, but with no rough ETA.

But hey, if you want this to work and will keep poking at it, fine by me! I appreciate all the effort you're spending on it. It's very nice to see, I don't mean to be a downer ;) I've just been down this road and opted for the simpler approach.

**Comment by sineer** [comment]
Yep I understand what you are saying completely :-) 

I have so many experimental feature I need in iocage that I had in mind for too long now that makes me mad so yeah I will end up heavily hacking current develop version... I really want to see zrep working with iocage asap.. zfs replication is key for me and at last I've done the experiments earlier and I know how to do it now! 

Your refactoring of the basejail is a lot cleaner than my sparsejail hack I did earlier and so by rebasing on it I will be able to cherry pick future fixes ;-)

I really need iocage push/pull and remote/branch ability this year even if it means a messy hack...

Thanks for all your work!

**Comment by skarekrow** [comment]
I totally understand! Good luck, and thanks for the kind words :)

**Pull request closed without merging**
