### PR TITLE
Speed up iocage by caching the list of jail datasets.

### PR DESCRIPTION
**Pull request by freqlabs**
I didn't expect a picture of Zoidberg to be taken seriously, it was meant only in good humor. I made this for you. I'm sorry.

### CODE REVIEW

**Comment by pannon** [comment]
Sure it was great humor for early teenagers. Obviously you enjoy watching cartoons and create memes from your favorites, which you then like to share here on GH.

Also this PR shows how you misinterpreted the comment about a global dataset list. The intention was to call it once only via ioc-globals not every time a function runs.

**Comment by freqlabs** [comment]
Ah you're right, this obviously won't work. I should have just let you do it to begin with. :/

Let me just remind you, it was your suggestion to PR my method for getting properties. I personally have no incentive to write the PRs you asked for, but I thought it would be nice to contribute back to a project I appreciate. I emailed you two weeks ago at your request, detailing my thoughts and proposed course of action, and asked for your feedback. After a week with no response, I assumed you didn't get my email and sent a non-intrusive PR hoping to get a discussion started. You have had no part in this discussion until jumping in yesterday with the proclamation that you haven't read the pages of explanation I'd written in support of my strategy but you had a good idea that maybe I was going about everything the wrong way.

I'm sorry if you were offended by my reference to a cartoon. I do enjoy cartoons and humor, and I failed to think that it might actually make you feel bad rather than make you grin. If anything that image was projecting how I felt I was being treated.

**Comment by pannon** [comment]
@freqlabs I have not received a single email from you ever.

**Comment by freqlabs** [comment]
Nevertheless, I sent an email at the end of July to your gmail address listed in the iocage help under the authors section. I will prefer not to carry on in this venue so please direct further inquiries to either my email or a private message in IRC. Thank you, sir, and good day.

**Pull request closed without merging**
